# Generated by Django 3.2.8 on 2021-12-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Boss_name', models.CharField(default='N/A', max_length=200)),
                ('_Boss_description', models.CharField(default='N/A', max_length=200)),
                ('_Num_lives', models.IntegerField(default=0)),
                ('_Correct_answers', models.IntegerField(default=0)),
                ('_Is_available', models.BooleanField(default=False)),
                ('_Boss_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_course_name', models.CharField(max_length=200)),
                ('_section_number', models.IntegerField(default=0)),
                ('_course_id', models.IntegerField(default=0)),
                ('_curr_XP', models.IntegerField(default=0)),
                ('_total_XP', models.IntegerField(default=0)),
                ('_course_level', models.IntegerField(default=1)),
                ('_max_XP', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course_General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_course_name', models.CharField(max_length=200)),
                ('_section_number', models.IntegerField(default=0)),
                ('_course_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Improve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Improve_name', models.CharField(default='Topics to improve on', max_length=200)),
                ('_Is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Quest_name', models.CharField(default='N/A', max_length=200)),
                ('_Quest_description', models.CharField(default='N/A', max_length=200)),
                ('_Num_lives', models.IntegerField(default=0)),
                ('_Correct_answers', models.IntegerField(default=0)),
                ('_Is_available', models.BooleanField(default=False)),
                ('_Is_completed', models.BooleanField(default=False)),
                ('_Quest_type', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
            ],
        ),
        migrations.CreateModel(
            name='Recs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Recs_name', models.CharField(default='N/A', max_length=200)),
                ('_Is_available', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Topic_text', models.CharField(default='N/A', max_length=200)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.recs')),
            ],
        ),
        migrations.CreateModel(
            name='Student_courseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_student_name', models.CharField(max_length=200)),
                ('_curr_XP', models.IntegerField(default=0)),
                ('_coins', models.IntegerField(default=0)),
                ('course_general', models.ManyToManyField(to='homepage.Course_General')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_curr_XP', models.IntegerField(default=0)),
                ('_coins', models.IntegerField(default=0)),
                ('_course_id', models.IntegerField(default=0)),
                ('_course_name', models.CharField(default='N/A', max_length=200)),
                ('_level', models.IntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(default='N/A', max_length=200)),
                ('_description', models.CharField(default='N/A', max_length=200)),
                ('_cost', models.IntegerField(default=0)),
                ('_id', models.CharField(default='N/A', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
            ],
        ),
        migrations.CreateModel(
            name='SideQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Quest_name', models.CharField(default='N/A', max_length=200)),
                ('_Quest_description', models.CharField(default='N/A', max_length=200)),
                ('_Num_lives', models.IntegerField(default=0)),
                ('_Correct_answers', models.IntegerField(default=0)),
                ('_Is_available', models.BooleanField(default=False)),
                ('_Quest_type', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Question_text', models.CharField(default='N/A', max_length=200)),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.boss')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.quest')),
                ('sidequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.sidequest')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.student_course'),
        ),
        migrations.CreateModel(
            name='ImproveTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_ImproveTopic_text', models.CharField(default='N/A', max_length=200)),
                ('improvetopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.improve')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Date_text', models.CharField(default='N/A', max_length=200)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.quest')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='specific_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.student_courselist'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_choice_text', models.CharField(default='N/A', max_length=200)),
                ('_isCorrectChoice', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.question')),
            ],
        ),
        migrations.CreateModel(
            name='bossDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_bossDate_text', models.CharField(default='N/A', max_length=200)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.boss')),
            ],
        ),
        migrations.AddField(
            model_name='boss',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.course'),
        ),
    ]
