# Generated by Django 3.2.8 on 2021-11-16 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_course_name', models.CharField(max_length=200)),
                ('_section_number', models.IntegerField(default=0)),
                ('_curr_XP', models.IntegerField(default=0)),
                ('_total_XP', models.IntegerField(default=0)),
                ('_course_level', models.IntegerField(default=1)),
                ('_max_XP', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Quest_name', models.CharField(default='N/A', max_length=200)),
                ('_Quest_description', models.CharField(default='N/A', max_length=200)),
                ('_Num_lives', models.IntegerField(default=0)),
                ('_Correct_answers', models.IntegerField(default=0)),
                ('_Is_available', models.BooleanField(default=False)),
                ('_Quest_type', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_Question_text', models.CharField(default='N/A', max_length=200)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_choice_text', models.CharField(default='N/A', max_length=200)),
                ('_isCorrectChoice', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.question')),
            ],
        ),
    ]
